title: t(h)inker
author: Nguyễn Mai Hương / Sierra Nguyen
email: maihuongnguyen1603@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Recently worked on: VietLit - A Vietnamese online literature platform.
theme: minima

minima:
  social_links:
    github:  ngmaihuong
    facebook: vietlit.community

show_excerpts: false

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#  - about.md

plugins:
  - jemoji
